// <auto-generated />
using System;
using Aplikacja_wspierajaca_rozwoj_dziecka.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Aplikacja_wspierajaca_rozwoj_dziecka.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251118214441_InicjalnaMigracja2")]
    partial class InicjalnaMigracja2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AktywnoscUmiejetnosc", b =>
                {
                    b.Property<int>("AktywnosciId")
                        .HasColumnType("int");

                    b.Property<int>("UmiejetnosciId")
                        .HasColumnType("int");

                    b.HasKey("AktywnosciId", "UmiejetnosciId");

                    b.HasIndex("UmiejetnosciId");

                    b.ToTable("AktywnosciUmiejetnosci", (string)null);
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Aktywnosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Kierunek")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("SzacowanyCzasMinuty")
                        .HasColumnType("int");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ZalecanyWiekDoRoku")
                        .HasColumnType("int");

                    b.Property<int?>("ZalecanyWiekOdRoku")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Aktywnosci");
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Dziecko", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataUrodzenia")
                        .HasColumnType("date");

                    b.Property<string>("Imie")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nazwisko")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notatki")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Dzieci");
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.DzieckoUmiejetnosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataStatusu")
                        .HasColumnType("datetime2");

                    b.Property<int>("DzieckoId")
                        .HasColumnType("int");

                    b.Property<string>("Komentarz")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UmiejetnoscId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UmiejetnoscId");

                    b.HasIndex("DzieckoId", "UmiejetnoscId")
                        .IsUnique();

                    b.ToTable("DzieckoUmiejetnosci");
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.DziennikAktywnosci", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AktywnoscId")
                        .HasColumnType("int");

                    b.Property<int?>("CzasTrwaniaMinuty")
                        .HasColumnType("int");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<int>("DzieckoId")
                        .HasColumnType("int");

                    b.Property<string>("Notatki")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("OcenaReakcjiDziecka")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AktywnoscId");

                    b.HasIndex("DzieckoId");

                    b.ToTable("DziennikiAktywnosci");
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Umiejetnosc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("CzyWlasna")
                        .HasColumnType("bit");

                    b.Property<int>("Kierunek")
                        .HasColumnType("int");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Opis")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("ZalecanyWiekDoRoku")
                        .HasColumnType("int");

                    b.Property<int?>("ZalecanyWiekOdRoku")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Umiejetnosci");
                });

            modelBuilder.Entity("AktywnoscUmiejetnosc", b =>
                {
                    b.HasOne("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Aktywnosc", null)
                        .WithMany()
                        .HasForeignKey("AktywnosciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Umiejetnosc", null)
                        .WithMany()
                        .HasForeignKey("UmiejetnosciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.DzieckoUmiejetnosc", b =>
                {
                    b.HasOne("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Dziecko", "Dziecko")
                        .WithMany("UmiejetnosciDziecka")
                        .HasForeignKey("DzieckoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Umiejetnosc", "Umiejetnosc")
                        .WithMany("UmiejetnosciDzieci")
                        .HasForeignKey("UmiejetnoscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dziecko");

                    b.Navigation("Umiejetnosc");
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.DziennikAktywnosci", b =>
                {
                    b.HasOne("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Aktywnosc", "Aktywnosc")
                        .WithMany("DziennikiAktywnosci")
                        .HasForeignKey("AktywnoscId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Dziecko", "Dziecko")
                        .WithMany("DziennikiAktywnosci")
                        .HasForeignKey("DzieckoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Aktywnosc");

                    b.Navigation("Dziecko");
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Aktywnosc", b =>
                {
                    b.Navigation("DziennikiAktywnosci");
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Dziecko", b =>
                {
                    b.Navigation("DziennikiAktywnosci");

                    b.Navigation("UmiejetnosciDziecka");
                });

            modelBuilder.Entity("Aplikacja_wspierajaca_rozwoj_dziecka.Models.Umiejetnosc", b =>
                {
                    b.Navigation("UmiejetnosciDzieci");
                });
#pragma warning restore 612, 618
        }
    }
}
